# create a file: 15_specialist_agents.py
import os
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, AIMessage

load_dotenv()

llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash", temperature=0)

# -------------------------------------------------------
# Researcher Agent
# Scope: gather and synthesise raw information
# Tools it would have in production: web search, document retrieval, MCP servers
# -------------------------------------------------------
def researcher_agent(state: dict) -> dict:
    """
    Receives the task and produces structured research findings.
    
    In production this agent would use the web search tool and MCP integrations
    from Parts 4–5. Here we simulate structured research output so the rest
    of the pipeline runs end-to-end without external API keys.
    """
    task = state["task"]
    
    prompt = f"""You are a specialist research agent. Your only job is to gather and 
synthesise factual information. Do NOT write summaries or drafts — output raw findings only.

Task: {task}

Produce a structured list of key findings. Each finding should be a concrete, 
specific fact. Format as numbered bullet points. Do not editorialize."""

    response = llm.invoke([HumanMessage(content=prompt)])
    findings = response.content
    
    print(f"\n[Researcher] Completed. Found {len(findings.split(chr(10)))} lines of findings.")
    
    return {
        "research_findings": findings,
        "messages": [AIMessage(content=f"[Researcher] {findings}", name="researcher")]
    }


# -------------------------------------------------------
# Writer Agent
# Scope: transform raw findings into polished prose
# -------------------------------------------------------
def writer_agent(state: dict) -> dict:
    """
    Receives research findings and produces a polished executive summary.
    
    Notice it reads from state["research_findings"] — it does NOT need
    to re-read the full message history. This isolation is intentional.
    """
    findings = state["research_findings"]
    task = state["task"]
    
    prompt = f"""You are a specialist writing agent. Your only job is to transform 
raw research findings into clear, professional prose.

Original task: {task}

Research findings to synthesise:
{findings}

Write an executive summary (3–4 paragraphs). Be concrete. Use specific facts from 
the findings. Do not invent information not present in the findings."""

    response = llm.invoke([HumanMessage(content=prompt)])
    draft = response.content
    
    print(f"\n[Writer] Draft complete ({len(draft)} characters).")
    
    return {
        "draft_content": draft,
        "messages": [AIMessage(content=f"[Writer] {draft}", name="writer")]
    }


# -------------------------------------------------------
# Notifier Agent
# Scope: format and deliver the output
# In production: would call a Slack MCP server or email tool from Part 4
# -------------------------------------------------------
def notifier_agent(state: dict) -> dict:
    """
    Formats the draft for delivery and simulates sending it.
    
    In a real system this would use the Slack MCP tool we built in Part 4.
    Here it formats and prints the message that would be sent.
    """
    draft = state["draft_content"]
    task = state["task"]
    
    # Simulate formatting for Slack's markdown dialect
    slack_message = f"""*📋 Research Summary*
_Task: {task}_

{draft}

---
_Generated by the Research Team Agent • {os.getenv("USER", "system")}_"""
    
    print(f"\n[Notifier] Message formatted and ready to send:")
    print("-" * 60)
    print(slack_message[:500] + "..." if len(slack_message) > 500 else slack_message)
    print("-" * 60)
    
    return {
        "messages": [AIMessage(
            content=f"[Notifier] Message delivered successfully. {len(slack_message)} characters.",
            name="notifier"
        )]
    }


# Quick sanity test — run each agent in isolation
if __name__ == "__main__":
    test_state = {
        "task": "Summarise the main advantages of vector databases over traditional relational databases for AI applications.",
        "messages": [],
        "research_findings": "",
        "draft_content": "",
        "next_agent": ""
    }
    
    print("=== Testing Researcher ===")
    result = researcher_agent(test_state)
    test_state.update(result)
    
    print("\n=== Testing Writer ===")
    result = writer_agent(test_state)
    test_state.update(result)
    
    print("\n=== Testing Notifier ===")
    result = notifier_agent(test_state)
    
    print("\n✓ All agents tested successfully in isolation.")
